language: go
install:
  - go get -t
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - ./generate.sh
  - go test -coverprofile=coverage.out
after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -package=imdario/xdr -repotoken $COVERALLS_TOKEN
